<?php

namespace Admin\Controller;

use App\Controller\AppController as BaseController;
use Cake\Core\Configure;
use Cake\Event\Event;

/**
 * @property bool|object Menus
 * @property bool layout
 */
class AppController extends BaseController
{
    public $imageFields = [];

    public function initialize()
    {
        parent::initialize();
    }

    /**
     * Set field boolean
     *
     * @param string $field
     */
    public function set_active($field = 'status')
    {
        $this->autoRender = false;

        if($this->request->is('ajax')) {
            $model = $this->modelClass;
            if(!empty($this->request->params['plugin'])) {
                $model = str_replace($this->request->params['plugin'].'.', '', $model);
            }

            $entity = $this->$model->get($this->request->data['id']);
            $entity->$field =  $this->request->data[$field];

            if ($this->$model->save($entity)) {
                echo json_encode(['status' => true]);
            }
        }
    }

    /**
     * @param Event $event
     */
    public function beforeRender(Event $event)
    {
        $this->set('imageFields', $this->imageFields);
        parent::beforeRender($event); // TODO: Change the autogenerated stub
    }
}
